@startuml class
skinparam nodesep 50

enum TipoAcademicoEnum <<Enum>> {
  ALUNO
  PROFESSOR
  TECNICOADM
}

enum TipoMidiaEnum <<Enum>> {
  MUSICA
  VIDEO
  PODCAST
  LIVRO
}

abstract class Usuario {
  -nome : String
  -ultimoNome : String
  -email : String
  -senha : char[]
  -credito : Currency
  -midiasAdquiridas : List<Midia> 
  -midiasfavoritas : Map<TipoMidiaEnum, List<Midia>>
  ---
  +visualizarMidia(Stirng nomeMidia) : Midia 
  +adicionarCredito(Currency valor) : void 
  +executarMidiaPlayer(String nomeMidiaPlayer) : MidiaPlayer 
  +comprarMidia(Stirng nomeMidia) : Midia 
  +venderMidia(Stirng nomeMidia) : void 
  +downloadMidia(Stirng nomeMidia) : void 
  +adicionarMidiaEmListaFavorito(Midia midia) : void 
  +visualizarCreditos() : Currency
}

class Academico {
  -tipo : TipoAcademicoEnum
}

class Autor {
  ---
  +criarMidia() : Midia
  +CriarAlbum() : Album
  +removerMidia(Midia midia) : void
  +AtualizarMidia(Midia midia) : void
}

class Administrador {
  ---
  +removerAcademico(Usuario usuario) : void
  +removerMidia(Midia midia) : void
}

class Album {
  -musicas : List<Musica>
  ---
  +adicionarMusica(Musica musica) : void
  +removerMusica(Musica musica) : void
  +exibirMusicas() : List<Musica> 
}

abstract class Midia {
  -nome : String
  -descricao : String
  -imagem : byte[]
  -preco : Currency
  -autores : List<Autor>
  -conteudo : byte[]
  -dataCriacao : Date
  -pagavel: boolean
  ---
  +visualizar() : void
  +comprar() : void 
  +vender() : void
  +download() : Midia
}

abstract class MidiaPlayer {
  -duracao : LocalTime
  ---
  +executar() : void
}

class Dashboard {
  ---
  +visualizarVendas(): void
}

class Livro {
  -numeroPaginas : Int
  -categorias : List<String>
}

class Musica {
  -categorias : List<String> 
}

class Video {
  -categorias : List<String> 
}

class Podcast {
  -categorias : List<String> 
}

Autor "1" *-- "1..*" Midia : cria > 

Usuario o-- Midia

Academico *-- TipoAcademicoEnum
Usuario *-- TipoMidiaEnum

Usuario <|-- Academico : < é um
Academico <|-- Autor : < é um (se criou 1 ou mais midias)
Usuario <|-- Administrador: < é uma

Midia <|-- Livro  : < é uma
Midia <|-- MidiaPlayer : < é uma
MidiaPlayer <|-- Video : < é um
MidiaPlayer <|-- Podcast : < é um

MidiaPlayer <|-- Musica : < é um
Musica "1..* \n - Faixa" --o "0" Album : < tem

interface VisualizarMidia <<Interface>> 
interface RemoverMidia <<Interface>> 
interface RemoverAcademico <<Interface>> 
interface AtualizarMidia <<Interface>> 
interface AdicionarCredito <<Interface>> 
interface CriarAlbum <<Interface>> 
interface VisualizarAlbum <<Interface>> 

VisualizarAlbum <|.. Academico
CriarAlbum <|.. Autor
AdicionarCredito <|.. Usuario
VisualizarMidia <|.. Usuario
RemoverMidia <|.. Autor
RemoverMidia <|.. Administrador
RemoverAcademico <|.. Administrador
AtualizarMidia <|.. Autor
Administrador --> Dashboard : <<delegates>>

interface ExecutarMidiaPlayer <<Interface>> 
interface ComprarMidia <<Interface>> 
interface VenderMidia <<Interface>> 
interface DownloadMidia <<Interface>> 
interface AdicionarMidiaEmListaFavorito <<Interface>> 
interface VisualizarCreditos <<Interface>> 

VisualizarCreditos <|.. Usuario
AdicionarMidiaEmListaFavorito <|.. Usuario
ExecutarMidiaPlayer <|.. Usuario
ComprarMidia <|.. Usuario
VenderMidia <|.. Usuario
DownloadMidia <|.. Usuario


hide Dashboard attributes
hide TipoAcademicoEnum methods
hide TipoMidiaEnum methods


@enduml